#Gemfile
source 'https://rubygems.org'

gem 'rake'
gem 'sass'
gem 'zip'
#gem 'prmd'
gem 'opal', '~> 0.9.0'
gem 'opal-jquery', '~> 0.4.0'
gem 'vector2d', "~> 2.1.0"
gem 'pry'
gem 'pry-byebug'  # for debugging on ruby lavel
gem 'graphviz'
gem 'bundler'
gem 'redcarpet'
gem 'json-schema-generator'
gem 'wortsammler', "~> 1.0.2"
gem 'neatjson'