#Gemfile
source 'https://rubygems.org'
ruby "~>2.4.1"

gem 'rake'
gem 'sass'
gem 'zip'
#gem 'prmd'
gem 'opal', '~> 0.10.6'
gem 'opal-jquery', '~> 0.4.2'
gem 'vector2d', "~> 2.1.0"
gem 'pry'
#gem 'pry-byebug'  # for debugging on ruby lavel
gem 'graphviz'
gem 'bundler'
gem 'redcarpet'
gem 'json-schema-generator'
gem 'neatjson'


# had trouble to install nokogiri on windows
# so I build the manual on mac os only
install_if -> { RUBY_PLATFORM =~ /darwin/ } do
  gem 'wortsammler', "~> 1.0.2"
end