require 'opal'
require 'opal-jquery'
require 'vector2d'
require 'opal-neatjson'
require 'opal-ajv'
#require 'math'

require 'consolelogger'
require 'harpnotes'
require 'abc_to_harpnotes_factory'
require 'abc2svg_to_harpnotes'

#require 'opal-raphael'
require 'opal-jspdf'
require 'opal-jszip'
require 'opal-musicaljs'
require 'svg_engine'
require 'pdf_engine'
require 'i18n'
require 'init_conf'
require 'command-controller'
require 'controller'
require 'controller-nw'
require 'controller_command_definitions'
require 'harpnote_player'
require 'text_pane'
require 'opal-dropboxjs'
require 'opal-jqconsole'
require 'confstack'
require 'opal-abc2svg'
require 'opal-w2ui'
require 'version'
require 'user-interface.js'
require 'config-form'
require 'snippet_editor'

puts "now starting zupfnoter"
puts "zupfnoter is now running"