# Rakefile
require 'opal'
require 'opal-jquery'

desc "Build our app to build.js"
task :build do
  env = Opal::Environment.new
  env.append_path "."

  File.open("build.js", "w+") do |out|
    out << env["application"].to_s
  end
end

desc "Build the documentation"
task :doc do
	sh "yard doc . --verbose --backtrace --protected --private"
	sh "yard graph -f doc/diagram.dot -d --verbose --backtrace --full --protected --private"

end
